### ISSUE TITLE
File infection errors

### ISSUE THREAD

**Issue by grcasanova** [SandPox/Polymorphic#1]
The infect routine will mostly fail either because wrongly recognizing uninfected files as already infected or because of memory errors (handled).
This leads to almost 95% of .exe/.dll files not being touched by the program.

**Comment by SandPox** [comment]
not my code, I'm upload it for educate purpose only, feel free to make pull request

**Comment by grcasanova** [comment]
@SandPox would you like to join me in the debugging of this code?

**Comment by SandPox** [comment]
i'm current busy with school stuff so I can't, sorry!
